### ISSUE TITLE
Example with fixed width or max-width

### ISSUE THREAD

**Issue by dlzi** [arnaudleray/pocketgrid#1]
Hi there,

Great stuff. I really like the idea behind pocketgrid. 

Just one thing. Could you create an example for fixed width or max-width? 

Thanks.

**Comment by arnaudleray** [comment]
Hi!
Thanks for your suggestion.
I'll try to add a max-width example as soon as possible!

**Comment by arnaudleray** [comment]
Done.
I added a [max-width example](http://arnaudleray.github.com/pocketgrid/examples/max-width.html) and a [fixed-width example](http://arnaudleray.github.com/pocketgrid/examples/fixed-width-responsive.html).

Is it what you were looking for?

**Comment by dlzi** [comment]
Hey there.

Great. It's exactly that. 

Thanks.

**Comment by arnaudleray** [comment]
Great. I close the ticket.

Thanks.
