### ISSUE TITLE
Bower install please :)

### ISSUE THREAD

**Issue by kristianmandrup** [arnaudleray/pocketgrid#12]
Do I really have to manually download it to use it, end of 2014? >)
Thanks!

**Comment by kristianmandrup** [comment]
needs `bower.json` with a `main` entry ;)

**Comment by adonald** [comment]
I'm sure he'd accept a pull request!

**Comment by kristianmandrup** [comment]
Done :)

**Comment by L1lle** [comment]
Why has this issue been closed with done? I can't see a bower.json.
