### ISSUE TITLE
improve PocketGrid

### ISSUE THREAD

**Issue by Manfred62** [arnaudleray/pocketgrid#6]
Hi Arnaud,

I like and use PocketGrid very much. In my case I have changed it a little bit on line 6 in pocketgrid.css. It's now shorter. What do you think?

*, *:after, *:before {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box
}

**Comment by lithiumjake** [comment]
I do that too.  Even has the Paul Irish stamp of approval.  But someone, somewhere, might be relying on the default behavior for some of their components, so I completely understand why Pocket Grid scopes this to itself.

**Comment by arnaudleray** [comment]
Hi!

Lithiumjake is right: I only scope the PocketGrid classes to avoid compatibility problems with other libraries that may use other box-sizing values (for example, Bootstrap 2 uses the default box-sizing).

Many thanks for using PocketGrid!
